### ISSUE TITLE
ConvertListToString

### ISSUE THREAD

**Issue by ThatRendle** [asmak9/Asmak9.EssentialToolKit#2]
New issue because you closed the last one claiming your library provides "complex repetitive code wrappers".

From your most recent blog post:

```csharp
string content = utilityKit.ConvertListToString(list1, ";");
```

Built-in feature.

```csharp
string content = string.Join(';', list1);
```

**Comment by asmak9** [comment]
Thanks for the info. But, try converting List of type CustomerObj having customer name, customer email and customer ID as properties to string with your one line of piece of code only i.e.

`List<CustomerObj> list1`
